### ISSUE TITLE
Isn't seq helper equivalent to pipe/compose?

### ISSUE THREAD

**Issue by kujon** [polytypic/fastener#1]
First of all - what an awesomely informative codebase, just beautiful!

I noticed that there's a slight overcomplication in the docs (given that you're importing ramda already):

Basically:

``` javascript
const seq = (x, ...fs) => R.reduce((x, f) => f(x), x, fs);
```

works pretty much the same as `pipe`/`compose`, so you could rewrite the following:

``` javascript
seq(F.toZipper(data),
    F.downTo('contents'))
```

into:

``` javascript
R.pipe(F.toZipper,
    F.downTo('contents'))(data);
```

It's also got an unfortunate name, given ramda's `sequence` function, which does something different: http://ramdajs.com/0.21.0/docs/#sequence

**Comment by kujon** [comment]
Apologies, didn't notice `pipeU` definition further down the docs.

**Comment by polytypic** [comment]
No need to apologize. :)

I personally find it easier to read [code written in a top->down left->right order](http://theburningmonk.com/2014/12/being-visually-honest-with-f/) easier to read.  Which is why I prefer to write e.g. `seq(x, f, g)` rather than `R.pipe(f, g)(x)` or `R.compose(g, f)(x)`.

**Comment by kujon** [comment]
@polytypic - I think there's an additional benefit of defining `seq` first - you can have a non-functional programmer read this tutorial and understand it. Anyway - awesome codebase!
